name: CI

on:
  release:
    types: [created, published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: webhook payload
      run: |
        cat $GITHUB_EVENT_PATH
        TAG=$(jq --raw-output .release.tag_name "${{ github.event_path }}")
        echo "tag: ${TAG}"
